# Generated by Django 5.1.6 on 2025-03-10 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_author_recipe_created_on_recipe_update_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
