# Generated by Django 5.1.6 on 2025-03-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_rename_user_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
